"""FocusMoE 250M top-2: single-image inference."""

model = {'type': 'TriSourceDetector',
 'backbone': {'type': 'ConvNeXtMoE',
              'moe_indices': [[],
                              [0, 2],
                              [0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26],
                              [0, 2]],
              'arch': 'small',
              'drop_path_rate': 0.1,
              'moe_args': [{'type': 'focusgate',
                            'mid_scale': 1,
                            'n_routed_experts': 8,
                            'n_activated_experts': 2,
                            'route_scale': 1.0,
                            'gate_func_cfg': {'type': 'ModalityPriorCosineLogit',
                                              'init_t': 0.5,
                                              'norm_dim': 'legacy',
                                              'prior_strength': 0.3,
                                              'prior_floor': 0.0},
                            'specific_expert_indices': {'sar': [2, 3],
                                                        'rgb': [4, 5],
                                                        'ifr': [6, 7]},
                            'share_expert_indices': [0, 1],
                            'noisy_gating': False,
                            'act_func': 'softmax'}],
              'init_cfg': None},
 'neck': {'type': 'MultitaskFPN',
          'in_channels': [96, 192, 384, 768],
          'out_channels': 256,
          'extra_level': 1,
          'add_extra_convs': 'on_output',
          'num_outs': 5},
 'sar_bbox_head': {'type': 'GFLHead',
                   'num_classes': 26,
                   'in_channels': 256,
                   'stacked_convs': 4,
                   'feat_channels': 256,
                   'anchor_generator': {'type': 'AnchorGenerator',
                                        'ratios': [1.0],
                                        'octave_base_scale': 8,
                                        'scales_per_octave': 1,
                                        'strides': [8, 16, 32, 64, 128]},
                   'loss_cls': {'type': 'QualityFocalLoss',
                                'use_sigmoid': True,
                                'beta': 2.0,
                                'loss_weight': 1.0},
                   'loss_dfl': {'type': 'DistributionFocalLoss', 'loss_weight': 0.25},
                   'reg_max': 16,
                   'loss_bbox': {'type': 'GIoULoss', 'loss_weight': 2.0}},
 'rgb_rpn_head': {'type': 'OrientedRPNHead',
                  'in_channels': 256,
                  'feat_channels': 256,
                  'version': 'le90',
                  'anchor_generator': {'type': 'AnchorGenerator',
                                       'scales': [8],
                                       'ratios': [0.5, 1.0, 2.0],
                                       'strides': [4, 8, 16, 32, 64]},
                  'bbox_coder': {'type': 'MidpointOffsetCoder',
                                 'angle_range': 'le90',
                                 'target_means': [0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
                                 'target_stds': [1.0, 1.0, 1.0, 1.0, 0.5, 0.5]},
                  'loss_cls': {'type': 'CrossEntropyLoss', 'use_sigmoid': True, 'loss_weight': 1.0},
                  'loss_bbox': {'type': 'SmoothL1Loss',
                                'beta': 0.1111111111111111,
                                'loss_weight': 1.0}},
 'rgb_roi_head': {'type': 'OrientedStandardRoIHead',
                  'bbox_roi_extractor': {'type': 'RotatedSingleRoIExtractor',
                                         'roi_layer': {'type': 'RoIAlignRotated',
                                                       'out_size': 7,
                                                       'sample_num': 2,
                                                       'clockwise': True},
                                         'out_channels': 256,
                                         'featmap_strides': [4, 8, 16, 32]},
                  'bbox_head': {'type': 'RotatedShared2FCBBoxHead',
                                'in_channels': 256,
                                'fc_out_channels': 1024,
                                'roi_feat_size': 7,
                                'num_classes': 26,
                                'bbox_coder': {'type': 'DeltaXYWHAOBBoxCoder',
                                               'angle_range': 'le90',
                                               'norm_factor': None,
                                               'edge_swap': True,
                                               'proj_xy': True,
                                               'target_means': (0.0, 0.0, 0.0, 0.0, 0.0),
                                               'target_stds': (0.1, 0.1, 0.2, 0.2, 0.1)},
                                'reg_class_agnostic': True,
                                'loss_cls': {'type': 'CrossEntropyLoss',
                                             'use_sigmoid': False,
                                             'loss_weight': 1.0},
                                'loss_bbox': {'type': 'SmoothL1Loss',
                                              'beta': 1.0,
                                              'loss_weight': 1.0}}},
 'ifr_rpn_head': {'type': 'OrientedRPNHead',
                  'in_channels': 256,
                  'feat_channels': 256,
                  'version': 'le90',
                  'anchor_generator': {'type': 'AnchorGenerator',
                                       'scales': [8],
                                       'ratios': [0.5, 1.0, 2.0],
                                       'strides': [4, 8, 16, 32, 64]},
                  'bbox_coder': {'type': 'MidpointOffsetCoder',
                                 'angle_range': 'le90',
                                 'target_means': [0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
                                 'target_stds': [1.0, 1.0, 1.0, 1.0, 0.5, 0.5]},
                  'loss_cls': {'type': 'CrossEntropyLoss', 'use_sigmoid': True, 'loss_weight': 1.0},
                  'loss_bbox': {'type': 'SmoothL1Loss',
                                'beta': 0.1111111111111111,
                                'loss_weight': 1.0}},
 'ifr_roi_head': {'type': 'OrientedStandardRoIHead',
                  'bbox_roi_extractor': {'type': 'RotatedSingleRoIExtractor',
                                         'roi_layer': {'type': 'RoIAlignRotated',
                                                       'out_size': 7,
                                                       'sample_num': 2,
                                                       'clockwise': True},
                                         'out_channels': 256,
                                         'featmap_strides': [4, 8, 16, 32]},
                  'bbox_head': {'type': 'RotatedShared2FCBBoxHead',
                                'in_channels': 256,
                                'fc_out_channels': 1024,
                                'roi_feat_size': 7,
                                'num_classes': 26,
                                'bbox_coder': {'type': 'DeltaXYWHAOBBoxCoder',
                                               'angle_range': 'le90',
                                               'norm_factor': None,
                                               'edge_swap': True,
                                               'proj_xy': True,
                                               'target_means': (0.0, 0.0, 0.0, 0.0, 0.0),
                                               'target_stds': (0.1, 0.1, 0.2, 0.2, 0.1)},
                                'reg_class_agnostic': True,
                                'loss_cls': {'type': 'CrossEntropyLoss',
                                             'use_sigmoid': False,
                                             'loss_weight': 1.0},
                                'loss_bbox': {'type': 'SmoothL1Loss',
                                              'beta': 1.0,
                                              'loss_weight': 1.0}}},
 'sar_test_cfg': {'nms_pre': 1000,
                  'min_bbox_size': 0,
                  'score_thr': 0.05,
                  'nms': {'type': 'nms', 'iou_threshold': 0.6},
                  'max_per_img': 100},
 'rgb_test_cfg': {'rpn': {'nms_pre': 2000,
                          'max_per_img': 2000,
                          'nms': {'type': 'nms', 'iou_threshold': 0.8},
                          'min_bbox_size': 0},
                  'rcnn': {'nms_pre': 2000,
                           'min_bbox_size': 0,
                           'score_thr': 0.05,
                           'nms': {'iou_thr': 0.1},
                           'max_per_img': 2000}},
 'ifr_test_cfg': {'rpn': {'nms_pre': 2000,
                          'max_per_img': 2000,
                          'nms': {'type': 'nms', 'iou_threshold': 0.8},
                          'min_bbox_size': 0},
                  'rcnn': {'nms_pre': 2000,
                           'min_bbox_size': 0,
                           'score_thr': 0.05,
                           'nms': {'iou_thr': 0.1},
                           'max_per_img': 2000}}}

# SAR, RGB and IR preprocessing from the source configuration.
pipelines = {'sar': [{'type': 'LoadImageFromFile'},
         {'type': 'MultiScaleFlipAug',
          'img_scale': (800, 800),
          'flip': False,
          'transforms': [{'type': 'Resize', 'keep_ratio': True},
                         {'type': 'RandomFlip'},
                         {'type': 'Normalize',
                          'mean': [123.675, 116.28, 103.53],
                          'std': [58.395, 57.12, 57.375],
                          'to_rgb': True},
                         {'type': 'Pad', 'size_divisor': 32},
                         {'type': 'ImageToTensor', 'keys': ['img']},
                         {'type': 'Collect_subdataset', 'keys': ['img'], 'subdataset': 'sar'}]}],
 'rgb': [{'type': 'LoadImageFromFile'},
         {'type': 'MultiScaleFlipAug',
          'img_scale': (800, 800),
          'flip': False,
          'transforms': [{'type': 'RResize'},
                         {'type': 'Normalize',
                          'mean': [123.675, 116.28, 103.53],
                          'std': [58.395, 57.12, 57.375],
                          'to_rgb': True},
                         {'type': 'Pad', 'size_divisor': 32},
                         {'type': 'DefaultFormatBundle'},
                         {'type': 'Collect_subdataset', 'keys': ['img'], 'subdataset': 'rgb'}]}],
 'ir': [{'type': 'LoadImageFromFile'},
        {'type': 'MultiScaleFlipAug',
         'img_scale': (800, 800),
         'flip': False,
         'transforms': [{'type': 'RResize'},
                        {'type': 'Normalize',
                         'mean': [123.675, 116.28, 103.53],
                         'std': [58.395, 57.12, 57.375],
                         'to_rgb': True},
                        {'type': 'Pad', 'size_divisor': 32},
                        {'type': 'DefaultFormatBundle'},
                        {'type': 'Collect_subdataset', 'keys': ['img'], 'subdataset': 'ifr'}]}]}
